#!/bin/bash -e

usage() {
    echo "

    This script takes in a file where every line is a database accession number and then searches
    the ENA database for sequences pertaining to it.  Couple notes. First, we're only searching the
    assembly database. If somebody has sequenced a strain but didn't bother assembling and uploading
    it we miss it. Second, we're literally just searching the accession number (i.e. NCTC10); if 
    somebody decided to get cute with naming we miss it. 

    3 required options:

    -i, --input:    path to input db
    -o, --output:   Path to desired output base directory. Within this folder, the 
                    structure will be database_accession/assembly_accession/*
    "
}

# get ena assembly accession number
check_ena_assembly() {

    # make header
    #echo -e ""$3"_Number\taccession\tversion\tassembly_name\tdescription" > $2
    rm -f $2 2> /dev/null
    touch $2
   
    # read in the list of db accessions
    cut -f2 $1 | tr -d ' ' | while read -r db_acc; do
        space=FALSE
        db_acc_with_space=$(echo $db_acc | sed "s/$3/$3+/")
        db_acc_with_realspace=$(echo $db_acc | sed "s/$3/$3 /")
    
        # real stupid way to check if search failed
        prev=$(wc -l $2)
        
        # if we get a hit, we append it to our file
        curl -X GET -s "https://www.ebi.ac.uk/ena/portal/api/search?result=assembly&query=strain=$db_acc" | awk -v acc="$db_acc_with_realspace" '{if(NR!=1){printf "%s\t%s\n", acc, $1}}' >> $2
        
        # we're checking if it was found
        next=$(wc -l $2)
        if [[ $prev == $next ]]; then 
            curl -X GET -s "https://www.ebi.ac.uk/ena/portal/api/search?result=assembly&query=strain=%22$db_acc_with_space%22" | awk -v acc="$db_acc_with_realspace" '{if(NR!=1){printf "%s\t%s", acc, $1}}' >> $2
            next=$(wc -l $2)
            #[[ $prev == $next ]] && echo "$db_acc not found" 
        #else
            #echo "$db_acc found"
        fi
    done
}

main() {
    INPUT="./db_accessions"
    OUTPUT="./hi"
    TYPE="NCTC"
    for i in "$@"; do
    case $i in 
        -i|--input)
        INPUT=$2
        shift
        shift
        ;;
        -t|--type)
        TYPE=$2
        shift
        shift
        ;;
        -o|--output)
        OUTPUT=$2
        shift
        shift
        ;;
        -h|--help)
        usage
        exit
        ;;
        *)
        ;;
    esac
    done
    mkdir -p $(dirname $OUTPUT)
    check_ena_assembly $INPUT $OUTPUT $TYPE
}
main "$@"
