#!/bin/bash

# extract the date using my memey heuristic from each nctc thing, then snag that subset which is before the min year (pre-antibiotics would be 1940)
get_min_years() {
    python extract_date.py $1 | grep -v '\-1' | awk -F'\t' -v min_year="$2" '{if($2 <= min_year){print $1}}' > /tmp/nctc_year_filtered_results
}

# get ena assembly accession number
check_ena_assembly() {
    echo -e "nctc_num\taccession\tversion\tassembly_name\tdescription" > $1
    while read lines; do
        nctc_acc=$(echo $lines | tr -d ' ')

        # real stupid way to check if search failed
        prev=$(wc -l $1)
        
        # search the ena with the NCTC accession number. couple things. first, we're only searching the assembly database. if somebody decided to not generate a full-fledged assembly from the sequence then we don't catch it. second, we're literally just searching the accession number. it is possible that we get results that are irrelevant, or somebody didn't label the strain label with the nctc number.
        # if we get a hit, we append it to our file
        curl -X GET -s "https://www.ebi.ac.uk/ena/portal/api/search?result=assembly&query=strain=$nctc_acc" | awk -v acc=$nctc_acc '{if(NR!=1){printf "%s\t%s\t%s\t%s\t%s\n", acc, $1, $2, $3, $4}}' >> $1
        #curl -X GET -s "https://www.ebi.ac.uk/ena/portal/api/search?result=wgs_set&query=strain=$nctc_acc" | awk -v acc=$nctc_acc '{if(NR!=1){printf "%s\t%s\n", acc, $1, $2}}' >> $1
        
        # we're checking if it was found
        next=$(wc -l $1)
        [[ $prev == $next ]] && echo "$nctc_acc not found" || echo "$nctc_acc found"
    done</tmp/nctc_year_filtered_results
}

# read in args
main() {

    MAX_YEAR=1940
    INPUT="../../../databases/2020-04-22_nctc_db.tsv"
    OUTPUT="./assembly_out"
    for i in "$@"; do
    case $i in

        # input file is the database generated from the nctc_trawler script
        -i|--input)
        INPUT="$2"
        shift
        shift
        ;;

        # max year to subset samples to
        -n|--max)
        MAX_YEAR="$2"
        shift
        shift
        ;;

        # output file
        -o|--output)
        OUTPUT="$2"
        shift
        shift
        ;;
        *)
        ;;
    esac
    done
    get_min_years $INPUT $MAX_YEAR
    check_ena_assembly $OUTPUT
}

main "$@"
