#!/bin/sh

usage() {
    echo "

    This script assumes that you have rgi loaded and working to submit jobs. Couple options:

    -i, --input:   path to file where every line is a path to a unzipped fasta assembly. Use find!
    -o, --output:   path to a file where every line is where rgi output should be dumped. Assumed to match the input!
    -j, --jobfile:  path to a jobtemplate file for O2
    
    "
}


SUBMITDEMJOBS_ab_jobscripts() {
   
    # make array of inputfiles 
    mapfile -t fasta_input_list < "$1"
    mapfile -t output_dir_list < "$3"

    # loop through index
    for i in "${!fasta_input_list[@]}"; do
       
        fasta="${fasta_input_list[i]}"
        outdir="${output_dir_list[i]}"
        fasta_fname="$(basename $fasta .fa)"
        
        output_basename="$outdir"/"$fasta_fname"_ab-search
        job_name="$output_basename".job
        
        cat $2 > $job_name
        echo "rgi main -i "$fasta" -o "$output_basename".rgi_out --exclude_nudge --clean --split_prodigal_jobs -n 12 --include_loose" >> $job_name
    done
}

main() {
    for i in "$@"; do
    case $i in 
        -i|--input)
        INPUTFILELIST=$2
        shift
        shift
        ;;
        -o|--output)
        OUTPUTDIRLIST=$2
        shift
        shift
        ;;
        -j|--jobfile)
        JOBTEMPLATE=$2
        shift
        shift
        ;;
        *)
        ;;
    esac
    done
    [ -f $INPUTFILELIST ] || die "$INPUTFILELIST doesn't exist"
    [ -f $JOBTEMPLATE ] || die "$JOBTEMPLATE doesn't exist"
    [ -f $OUTPUTDIRLIST ] || die "$OUTPUTDIRLIST doesn't exist"
    [ "$(wc -l < $INPUTFILELIST)" -eq "$(wc -l < $OUTPUTDIRLIST)" ] || die "Input file list doesn't have the same number of lines as output dir list"
    SUBMITDEMJOBS_ab_jobscripts $INPUTFILELIST $JOBTEMPLATE $OUTPUTDIRLIST
}

die() {
    printf 'error: %s.\n' "$1" >&2
    exit 1
}

main "$@"
