#!/bin/python
import sys
import pandas as pd
import re
if "-h" in sys.argv or "--help" in sys.argv:
    print("Outputs best guess for year isolated for each strain in CIP. \n'-1' if no data available.\n\nUse by running './extract_dates PATHTOCIPDB'")
    sys.exit()

x = pd.read_csv(sys.argv[1], sep='\t', index_col=0)
for index,row in x.iterrows():
    year_ext = None
    regex_for_year = "(?:19|20)\d{2}"
    d_i = re.findall(regex_for_year, str(row["Date_d'isolement"]))
    if len(d_i) != 0:
        year_ext=min(d_i)
    o_d = re.findall(regex_for_year, str(row['Other_designations_']))
    if year_ext == None and len(o_d)!=0:
        year_ext=min(o_d)
    if year_ext == None:
        print(row['Identification']+"\t"+"-1")
    else:
        print(row['Identification']+"\t"+year_ext)
